version: "3"

services:
  server:
    build: .
    restart: always
    ports:
      - 3000:3000
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  postgres_db:
