version: "3"

services:
  server:
    container_name: notes-app-server
    build: .
    depends_on:
      - postgres_db
    restart: always
    environment:
      - PSQL_HOST=postgres_db
      - POSTGRES_DB=notes
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 3000:3000
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=notes
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80

volumes:
  postgres_db:
